### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by xplicit** [davidfowl/HelloWorldVNext#2] opened 2014-05-27 08:58 UTC
My environment: 
Intel(R) Core(TM)2 Duo CPU     E4600  @ 2.40GHz 
Ubuntu 12.04 
mono 3.4.1 (master/09126b1)

I ran the following command:

   ab -c 30 -n 100000 http://testhost:8080/

HelloWorldVNext serves ~70 requests  per second. 

I compare it with the my fastcgi web server which works with nginx and mono (http://github.com/xplicit/HyperFastCgi) 
HyperFastCgi v0.3 managed (System.Web+ServiceStack) - ~2000 rps
HyperFastCgi v0.4  wrapper of libevent (System.Web+ServiceStack) - ~2400 rps
HyperFastCgi v0.4  wrapper of libevent (no System.Web, returns "Hello, World" similar to  HelloWorldVNext) ~7000 rps

When I remove nginx and directly return "Hello, world" to the client, I get ~10 000 rps

I did not look into vNext sources yet, but can guess that you might run into the mono cross-domain data passing issue. It's very slow on mono. On my machine calling `void Test()` method from another domain produces only 3000 (!) calls per second. And it's an "empty" method without data serialization.  If I used it in HyperFastCgi I would get only ~100 rps, which is near to vNext results. But I don't use it :) I found a way using native code and embedded mono API to call method in other domain with appropriate several millions calls per second. This looks like a dirty hack, but it works and produces good performance results.

**Comment by davidfowl** [comment] 2014-05-27 09:14
I'm not sure the performance results have anything to do with cross app domain calls. Best thing to do is to profile it and see where the problem is. It might be an issue with Nowin, or the runtime itself or mono. There's too little data to know right now.

**Comment by xplicit** [comment] 2014-05-27 10:14
You're right, profiling should go first. I ran profile and did not see binary serialization, which is a red flag of cross-domain communication. A lot of time is spent by zipsharp, and System.Threading.Thread.StartInternal looks strange. WaitOne consumes  most of the execution time. 
 And in real the performance is much better, than 70 rps. The issue is that server deadlocks after several hundreds of requests (that's why WaitOne consumes all the time!) and I can not measure performance accurately.

```
    1568 calls from:
            (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
            System.Threading.Thread:StartInternal ()
            System.Threading.Timer/Scheduler:SchedulerThread ()
            System.Threading.WaitHandle:WaitOne (int)
            System.Threading.WaitHandle:WaitOne (int,bool)
```

**Comment by xplicit** [comment] 2014-05-27 20:37
Because it's not performance issue, but deadlock in the mono runtime, I filled the bug.

https://bugzilla.xamarin.com/show_bug.cgi?id=20073

**Comment by davidfowl** [comment] 2014-05-28 02:20
@xplicit Thanks for filing this! I'm hoping we can flesh out these issues on mono :smile: . BTW do you want to take a stab at plugging your webserver into the ASP.NET vnext pipeline?

**Comment by xplicit** [comment] 2014-05-28 05:00
Yes, I am going to do it :) What I need is an ability to compile ASP.NET vNext on mono, at least parts which I have to deal with (for easier debugging issues on mono). It would also be great if pull requests from community are merged in the project tree. Yesterday, I spent some time to fix build.sh of KRuntime and after that I found that someone already did the staff and made pull request, but it did not merged. They say that they cannot take pull requests from the community yet.
And could you please point to the project/interface where to look at for starting plug-in server into vNext pipeline?

**Comment by davidfowl** [comment] 2014-05-28 05:43
@xplicit might be more effective to chat about it briefly in https://jabbr.net/#/rooms/AspNetvNext to go over the general design. You're booting the mono runtime right?

**Comment by xplicit** [comment] 2014-05-29 00:24
Yeap, I am working with mono/linux platform.

**Comment by xplicit** [comment] 2014-05-30 06:39
@davidfowl There is additional info about this hang:

Sockets don't close properly, when requests are handled. To see it you can check the following thing:

```
ps aux | grep mono | grep klr
```

get the PID of the running mono process

then type 

```
ls /proc/<PID>/fd
```

you'll see the list of opened handles by the application. Then if you type "http://localhost:8080/" in the browser (at least in mozilla firefox), and type again `ls /proc/<PID>/fd`, you'll see, that nothing has change, that means socket was opened, data "Hello, world" was sent, and socket was properly closed.

But if you run `ab -n 1 -c 1 http://localhost:8080/` and then check the socket list again, you'll see one additional descriptor. That means, socket was not closed properly. 
After `ab -n 1024 http://localhost:8080/` I get all the file descriptors available to the application run out. And new sockets can't be created. In this case, mono must throw an exception and you should handle it. But or mono does not throw it or exception is eaten by the application and I see hang instead of error.

And, of course, sockets must be properly closed no matter which client is used.

**Comment by davidfowl** [comment] 2014-05-30 06:49
@Bobris do you know of any known issues running Nowin on mono?

**Comment by Bobris** [comment] 2014-05-30 07:08
I benchmarked more than 65000 requests on Linux some time ago. So this could be something new. Enabling tracing there should be disconnects visible.

**Comment by davidfowl** [comment] 2014-05-30 07:15
@Bobris and you try running this sample with your tests?

**Comment by xplicit** [comment] 2014-05-30 07:23
@Bobris 
My current version of kre is KRE-mono45-x86.0.1-alpha-build-0476,
mono --version
Mono JIT compiler version 3.4.1 (master/5ed69a0 Wed May 28 06:31:59 NOVT 2014)
OS: Ubuntu linux 12.04

**Comment by davidfowl** [comment] 2014-05-30 07:44
@xplicit which sample are you using?

**Comment by xplicit** [comment] 2014-05-30 07:47
@davidfowl I run `k web` with https://github.com/davidfowl/HelloWorldVNext application 

```
cd src/helloworldweb
k web
```

**Comment by davidfowl** [comment] 2014-05-30 07:48
which one? there's 3 of them

**Comment by xplicit** [comment] 2014-05-30 07:49
Updated the comment above

**Comment by davidfowl** [comment] 2014-05-30 08:28
Ok @xplicit and @Bobris, to verify where the problem might be, I added another server, firefly in a submodule https://github.com/davidfowl/HelloWorldVNext/commit/38543a4744733533726c6db2da2a1941e80d2573. Now you should be able to do k web for nowin or k web-firefly for firefly. 

@xplicit, would you mind doing another run with firefly to see if the same problem occurs?

**Comment by xplicit** [comment] 2014-05-30 09:26
@davidfowl I try to compile firefly, there are some issues.
under ./nuget directory all of the file names should be lowercased, or they are cannot be found by xbuild, and lowercase NuGet.exe in build.sh script
and then I get 
/home/sergey/Projects/vNext/HelloWorldVNext/firefly/.nuget/nuget.targets: error : Error executing task Exec: Task does not have property "LogStandardErrorAsError" defined
will try to resolve it

**Comment by davidfowl** [comment] 2014-05-30 09:29
compile firefly? All you have to do is run kpm like before and run k web-firefly. You don't have to compile anything.

**Comment by xplicit** [comment] 2014-05-30 09:36
k web-firefly
Unable to load application or execute command 'web-firefly'

Sorry, that was from another directory. The real error looks like this
k web-firefly
Could not load file or assembly 'firefly' or one of its dependencies. The system cannot find the file specified.

**Comment by davidfowl** [comment] 2014-05-30 10:00
Did you run:

```
git submodue init
git submodule update
```

Firefly is source so you need to bring in the submodule.

**Comment by xplicit** [comment] 2014-05-30 10:03
yes, I did it. I was able to run firefly. To manage this I run `kpm restore` in firefly dir and change string 'firefly' to 'Firefly'  in project.json. Also I find it runs on other port 3001 instead of 8080. Now I am trying to check the issue.

**Comment by davidfowl** [comment] 2014-05-30 10:09
yea, it's all rough edges right now, sorry about that.

**Comment by xplicit** [comment] 2014-05-30 10:09
It works with firefly. Is there a way to change firefly listening host from 127.0.0.1 to 0.0.0.0?

**Comment by xplicit** [comment] 2014-05-30 10:15
From the same machine I get ~2500 requests per second. Want to try it from other.

**Comment by davidfowl** [comment] 2014-05-30 10:31
Change https://github.com/FireflyServer/firefly/blob/master/src/main/Firefly/ServerFactory.cs#L30 to IPAdress.Any.

You don't have to compile, just change and run k web-firefly

**Comment by xplicit** [comment] 2014-05-30 11:08
Finally I've got 4200 requests per second with web-firefly. AFAIR what I could get with managed code on my machine was ~5500 rps. So numbers are looking good. If you change listener to libevent for example, you'll get 8000-9000 rps

**Comment by davidfowl** [comment] 2014-05-30 15:43
@Bobris can you take a look at why Nowin isn't closing sockets?

**Comment by Bobris** [comment] 2014-05-30 15:55
I am still at work, you know money and other stuff :-). Is that possible to try it on Windows under mono. I don't have Linux installation normally... But I will try to look at it over weekend.

**Comment by davidfowl** [comment] 2014-05-30 16:00
@Bobris work is overrated :smile: . Of course, do it in your own time. I just wanted to make you aware :smile:

**Closed as completed** 2017-02-20 03:20 UTC
